### PR TITLE
Add all mobs to dungeon.

### PR DESCRIPTION
**Pull request by SinjiPrasetio**
This PR changes is :
✅  Added all mobs into all dungeons except below.
❌ TODO: lhz_dun03 and lhz_dun04 MVP (random fixed cordinate to summon MVP)

### CODE REVIEW

**Comment by sagunkho** [comment]
For some reason the mobs have not loaded, check PR run - https://github.com/horizonxyz/horizon/actions/runs/7296665371/job/19897742890?pr=143

no sign of `bra_dun01` and other newly added dungeons. Are they added to the include file?

**Comment by SinjiPrasetio** [comment]
Let me check my commit..

**Comment by SinjiPrasetio** [comment]
it's weird, the monster are spawning in my local. 
image
image

But not spawning in check.

**Comment by sagunkho** [comment]
There must be an issue in the workflow (on GitHub). Will create a new issue to check it later.

**Comment by SinjiPrasetio** [comment]
Hello, i've checked the latest check, i found the mob has been found
https://github.com/horizonxyz/horizon/actions/runs/7306235491/job/19910982122?pr=143
image

**Comment by sagunkho** [comment]
Great! I see champion jobs as well. I will merge this PR.

**Review by sagunkho — APPROVED** [review]
Looks good! Approved and ready for merge.

**Pull request merged**
